# Generated by Django 3.0.7 on 2020-06-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memer', '0002_auto_20200622_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeimages',
            name='meme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memer.Meme'),
        ),
    ]
