# Generated by Django 3.0.7 on 2020-06-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memer', '0003_auto_20200622_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeimages',
            name='meme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memerconnect', to='memer.Meme'),
        ),
    ]
