# Generated by Django 3.0.7 on 2020-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memer', '0004_auto_20200622_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memeimages',
            old_name='meme',
            new_name='parent_meme',
        ),
        migrations.AddField(
            model_name='meme',
            name='images',
            field=models.ManyToManyField(to='memer.MemeImages'),
        ),
    ]
