# Generated by Django 3.0.7 on 2020-06-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memer', '0005_auto_20200622_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='images',
        ),
    ]
