# Generated by Django 3.0.7 on 2020-06-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memer', '0006_remove_meme_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='score',
        ),
        migrations.AddField(
            model_name='memeimages',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
